EddyRivasLab/hmmer

- configure.ac
- src/Makefile.in
- src/compat/Makefile.in
- src/compat/strsep.c
- src/compat/strsep.h
- src/hmmdmstr.c
- src/p7_config.h.in
> H3 develop: build fixes for Solaris

- src/hmmc2.c
to prevent crashes when server sends more than 2GB of data to client.
> changed type of variable n in hmmc2.c/main to uint64_t 

- src/fm_ssv.c
- src/hmmerfm-exactmatch.c
- src/p7_tophits.c
Issue #11 in Infernal (https://github.com/EddyRivasLab/infernal/issues/11) highlights the possibility of random return values from the hit_sorter* functions used by qsort when all compared keys are equal. This branch fixes analogous situations in hmmer's develop (h3) branch. Please take a look at the comparison. 
There are two qsort helper functions that I did not edit. These are: cachedb.c:sort_seq() and hmmdmstr.c:hit_sorter(). Those use a different strategy that I think is 'ok' with respect to this issue of possible random return values, but see what you think. For example, cachedb:sort_seq() is: 
```
static int
sort_seq(const void *p1, const void *p2)
{
int cmp;
cmp  = (((HMMER_SEQ *)p1)->idx < ((HMMER_SEQ *)p2)->idx);
cmp -= (((HMMER_SEQ *)p1)->idx > ((HMMER_SEQ *)p2)->idx);
return …
```
> Proposed fix for possible qsort callback random return value

- src/hmmer.h
- src/p7_hmmfile.c
Making sure that `char *` is `const` whenever it is read-only.
> char * to const char *

- src/hmmer.h
- src/p7_pipeline.c
> Const getopts

- .travis.yml
This allows for cloning easel from the current repo.
As in my case, that line gets translated to
```
git clone -b develop https://github.com/horta/easel.git
```
> Use the current repo for cloning easel

- src/hmmsearch.c
- src/jackhmmer.c
- src/makehmmerdb.c
- src/nhmmer.c
- src/phmmer.c
This pull request accompanies and depends on infernal pull request
4 and easel pull request 46. It should only be accepted if those pull
requests are accepted also.
This pull request includes support for a new int (effectively boolean)
argument to the esl_sqio_ReadBlock() (both ascii and ncbi versions) of
<max_init_window>. When set to TRUE, this causes the function to
define windows identically for sequences regardless of their order
in a sequence file. When set to FALSE, this flag has *no* *effect*.
All hmmer calls in this pull request set <max_init_window> to FALSE
so these changes should have *no effect*.
In infernal, <max_init_window> is set to TRUE for some calls.
See the easel pull request 46 and infernal pull request 4 for more information.
> esl_sqio_ReadBlock() uses new argument max_init_window

- src/nhmmer.c
- src/p7_domaindef.c
In p7_domaindef.c, following a call to p7_Decoding(), line 897 was:
if (status == eslERANGE) return eslFAIL;
The comment says this is the result of repetitive garbage [J3/119-212],
which is certainly the case that has caused it to fire in my hands (in nhmmer).
The eslFAIL return value is handled gracefully in the calling function,
but since it returns immediately, the normal end-of-function cleanup
wasn't happening. That skipped cleanup is basically just the line:
p7_trace_Reuse(ddef->tr);
The result is that the next call to p7_OATrace() failed with:
Fatal exception (source file optacc.c, line 233):
trace not empty; needs to be Reuse()'d?
Abort trap: 6
The solution (in this pull request) is to force the trace to be reused
before returning eslFAIL:
if (status == eslERANGE) { …
> Force trace to be Reuse()'d after numeric overflow in p7_Decoding()

- documentation/man/nhmmer.man.in
- documentation/userguide/tutorial.tex
- src/nhmmer.c
- testsuite/testsuite.sqc
This is a much delayed fix for issue #171. 
If nhmmer is called without guidance on the input type, it tries to guess
whether the query is an HMM, MSA, or unaligned file of seqs. It previously
did this by trying to open the file first as an HMM, then as an MSA, and
finally as a sequence file - if it succeeded at any point, it would decide
this was the correct input type. This over-eager guessing strategy could
lead to unexpected results:
- when reading a sequence file with a single sequence, nhmmer would treat
the input as a one-sequence MSA; this is not intuitive.
- when reading a sequence file with many sequences all of the same length,
nhmmer would guess that this was an MSA, and smash them into a single query,
computing one model for the "MSA"; this is just plain wrong
This PR …
> Fix for iss#171: guessing query file format

- src/p7_domaindef.c
The change in this PR is simple: in rescore_isolated_domain(), if p7_Decoding() returns eslERANGE*, then the bg model is returned to its original form via a call to reparameterize_model() before rescore_isolated_domain() returns an eslFAIL status. Previously, it just returned the eslFAIL status without recovering bg, so that all subsequent work was done with a wrong (and highly biased) bg.
* (the eslERANGE result is assumed to mean that the target appears to be repetitive garbage, see Sean's comment in the code)
I've tested this on thousands of highly-repetitive models and sequences found in the raw data for a new Dfam release, and it works as expected: the rare eslERANGE result is handled gracefully (bg model is reset as it should be, subsequent work proceeds as normal). 
I've also …
> Fix for Isssue #198

- src/fm_general.c
- src/nhmmer.c
This PR addresses the concern raised in https://github.com/EddyRivasLab/hmmer/issues/195: nhmmer provides a confusing error message when the target database fails autodetection. 
The issue was that nhmmer's target autodetection code follows a path that ends in checking if the input is in the binary FMindex format, and those functions (in fm_general.c) were previously written to handle errors with a call to esl_fatal(). This would cause nhmmer to exit and give an FM-specific error, even though the file might be anything (Nick found the error with a mis-formatted embl file, and reproduced with an image file). The solution depends on changing fm_general.c error handling to do what it should always have done: return an error status, so that the calling function can clean up as appropriate. …
> Fix Iss#195 - confusing error message for badly-formatted target database

- Makefile.in
- configure.ac
- src/Makefile.in
This PR adds a 'install-strip' target, allowing to strip the hmmer3 binaries before installing them to the
desired target location, thereby reducing required disk space.
> add install-strip target

- src/impl_sse/Makefile.in
- src/impl_vmx/Makefile.in
Hi!
I got some relocation error at the linking stage while playing around with the code, and then noticed that the platform-specific code in `impl-sse` and `impl-vmx` was not built with `-fPIC` even after configuring with `./configure --enable-PIC`. Turns out both `Makefile.in` were not taking `${PIC_CFLAGS}` into account while compiling, so I fixed that in this PR.
> Fix Makefile not using PIC_CFLAGS when building platform-specific code

- src/nhmmer.c
Minor fix to add a space to an error message about unguessable alphabet.  Observed in issue #210
(problem message was: "Unable to guess alphabet for the FASTA-formattedquery file")
> nhmmer fix error msg

- Makefile.in
A minor tweak for Infernal:
Infernal's 'make distclean' calls 'make distclean' in its hmmer subdir. If configure hasn't been called in hmmer's subdir yet, then 'config.log' and 'config.status' won't exist, and a flagless 'rm' call on 'config.log' and 'config.status' will fail and exit in an error. I think the error is ignored but the distclean output still reports an error which is not ideal. This PR adds '-f' to the 'rm' call, making it mirror the analogous situation in easel's distclean commands.
I don't think this is important enough to worry about in infernal 1.1.4 which will include hmmer 3.3.2.
> distclean modification for config.log and config.status files

- src/makehmmerdb.c
This is a fix for https://github.com/EddyRivasLab/hmmer/issues/213.
The error was caused by incorrect sizes for some of the sequence elements
in the data structure underlying the FM-index-based binary representation
of the sequence database created with makehmmerdb. The error was a simple
matter of failing to initialize the value to zero before accumulating
length while reading the sequence (i.e. lengths could be effectively
random under certain memory access conditions).
Though the original issue only found an error when nhmmer search was
performed on a database produce by running makehmmerdb with the
--block_size flag, the error also could affect databases produced without
any makehmmerdb flag.
> Fix for nhmmer memory error - issue 213

- Makefile.in
make install{,-strip} fails if $PREFIX/{bin,share/man/man1} already exists as a directory but is owned by a different user:
```
[sjaenick@piggy:/vol/mgx-sw/src/tools/hmmer-3.3.2 ]$ make install
SUBDIR easel
SUBDIR miniapps
SUBDIR libdivsufsort
SUBDIR src
SUBDIR impl_sse
SUBDIR profmark
/usr/bin/install -c -d /vol/mgx-sw/bin
/usr/bin/install: cannot change permissions of ‘/vol/mgx-sw/bin’: Permission denied
Makefile:133: recipe for target 'install' failed
make: *** [install] Error 1
[sjaenick@piggy:/vol/mgx-sw/src/tools/hmmer-3.3.2 ]$ ls -ld /vol/mgx-sw/bin/
drwxrws--- 2 root mgxserv 9112 Jan 29 14:38 /vol/mgx-sw/bin/
```
This PR adds additional checks to the Makefile, only attempting to create the relevant directories if they don't exist yet.
> check targetdir existence before attempting to create it

- Makefile.in
- configure.ac
- src/Makefile.in
- src/hmmer.h
- src/impl_neon/00MANIFEST
- src/impl_neon/Makefile.in
- src/impl_neon/decoding.c
- src/impl_neon/fwdback.c
- src/impl_neon/impl_neon.h
- src/impl_neon/io.c
- src/impl_neon/mpi.c
- src/impl_neon/msvfilter.c
- src/impl_neon/null2.c
- src/impl_neon/optacc.c
- src/impl_neon/p7_omx.c
- src/impl_neon/p7_oprofile.c
- src/impl_neon/ssvfilter.c
- src/impl_neon/stotrace.c
- src/impl_neon/vitfilter.c
- src/impl_neon/vitscore.c
- src/p7_config.h.in
Supersedes #230, rebased to `h3-arm`.
You'll need `easel` checked out on the `master` branch to build. Compiles and passes all tests on my Raspberry Pi 4.
> Add platform-specific implementation for ARM using NEON

- src/p7_hmmfile.c
Hi !
It was reported in [althonos/pyhmmer#5](https://github.com/althonos/pyhmmer/issues/5) that the ASCII writer would segfault when writing a freshly created HMM.
It turns out that `p7_hmmfile_WriteASCII` reads from `hmm->consensus` before checking if the `p7H_CONS` flag is set. For HMMs without a consensus line set already, this will read from a NULL pointer.
> Fix `p7_hmmfile_WriteASCII` segfaulting on missing consensus sequences

- src/nhmmer.c
The following error can arise in edge case inputs:
% nhmmer --dna A.fa B.fa
Error: Invalid alphabet type in target for nhmmer. Expect DNA or RNA.
An example input that will produce this error is:
% cat A.fa
>seq1
AA
% cat B.fa
>seq1
AC
~~~
Note: The --dna flag tells nhmmer that the QUERY is in DNA format.
It does not assert anything about the target, and there isn't
a flag that does.
There is a check in the first step of reading the target that aims
to stop a user from providing a protein target sequence to nhmmer:
esl_sqfile_GuessAlphabet(dbfp, &q_type);
if (! (q_type == eslDNA || q_type == eslRNA))
p7_Fail("Invalid alphabet type in target for nhmmer. Expect DNA or RNA.\n");
The problem arises when esl_sqfile_GuessAlphabet() is unable to
guess the target alphabet. This can happen when …
> Fix for rare "Invalid alphabet type" nhmmer error

- documentation/man/alimask.man.in
- src/alimask.c
This commit addresses issue #237:
"Alimask crashes if asked to mask an alignment in a region that's outside the range of the alignment."
I've added range checks on all four of --alirange, --modelrange, --ali2model, and --model2ali. For all four:
- the smallest among all `<from>` positions must be >0
- for all ranges, `<to>` can not be less that `<from>`
- the largest among `<to>` positions is restricted as is described in the next paragraphs.
For (--alirange, --ali2model): `<to>` can not exceed the alignment length.
For (--modelrange, --model2ali):
- alimask works as before, computing the model that would be produced by hmmbuild (by numerous flags mirroring those from hmmbuild).
- for all ranges, `<to>` can not exceed the resulting model length.
The --ali2model required a bit of extra …
> Fix alimask out-of-range errors (iss #237)

- src/hmmer.h
- src/p7_domain.c
- src/p7_hit.c
- src/p7_tophits.c
Hi !
This PR adds new functions to clone a `P7_TOPHITS`, namely `p7_domain_Copy`, `p7_hit_Copy` and `p7_tophits_Clone`, which follow the copy/clone semantics of the rest of the code.
You may not have immediate use for it in HMMER, but I definitely need them for PyHMMER (where I actually implemented them, but they have their place in the upstream code). Basically, since the `p7_tophits_merge` function effectively consumes its second argument, this makes it unsound to use in Python, because reference counting means that several references may still exist to the second top hits. Copying the hits before merging solves the issue because the original object is then untouched.
> Add functions to clone a `P7_TOPHITS`

- src/nhmmer.c
This addresses https://github.com/EddyRivasLab/hmmer/issues/271.
In iss#271, running the command
% nhmmer --cpu 0 --dna query.fasta target.fasta
produces the following error:
Parse failed (sequence file assembly.fasta):
Line 2: unexpected char A; expected FASTA to start with >
The error arises when two things are true of the first sequence
in the target file:
(1) It does not contain all four nucleotide characters (e.g.
it contains only A,C, and Ts, and has no Gs)
(2) It is longer than the buffer length used when reading a
sequence in nhmmer (4000)
What's happening is:
(1) nhmmer calls esl_sqfile_GuessAlphabet() for the target sequence,
even if the --dna (or --rna) flag is set (around line 704 of nhmmer.c).
- This is bad. It should respect the --dna/--rna flag.
- That's fixed in this …
> Fix "Invalid alphabet type" error in nhmmer - iss#271

- src/p7_tophits.c
Hi !
In [althonos/pyhmmer#46](https://github.com/althonos/pyhmmer/issues/46) @zdk123 found out that `p7_tophits_Threshold` is not resetting domain counts, which may cause issues if the function is called more than once. I don't think it happens in HMMER, but it may happen in PyHMMER.
> Fix `p7_tophits_Threshold` not resetting domain counts
